version: "3.8"
services:
  mongo_insight:
    image: mongo
    ports:
      - "7675:27017"
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - app_network

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
volumes:
  mongodb:

networks:
  app_network:
    external: true