version: "3.8"
services:
  mongo_insight:
    image: mongo
    ports:
      - "7080:27017"
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: insighter_prod
      MONGO_INITDB_ROOT_PASSWORD: toTxH0aLcNCplv4icwRQA3nUvR
    networks:
      - app_network

volumes:
  mongodb:

networks:
  app_network:
    external: true