version: "3.8"
services:
  mongo_insight:
    image: mongo
    ports:
      - "7080:27017"
    restart: always
    volumes:
      - mongodb:/DB/Mongo/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - stage_network


volumes:
  mongodb:

networks:
  stage_network:
    external: true