version: "3.8"
services:
  mongo_insight:
    image: mongo
    ports:
      - "7080:27017"
    restart: always
    volumes:
      - mongodb:/DB/Mongo/data/db
    networks:
      - stage_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: insighter_stage
      MONGO_INITDB_ROOT_PASSWORD: 06nRVUHGoZyVCkpdrkU6UktLuJ

volumes:
  mongodb:

networks:
  stage_network:
    external: true